var div = document.getElementById("topbar");
var div1 = document.createElement("div");
var div2 = document.createElement("div");
var div3 = document.createElement("div");
var div4 = document.createElement("div");
var div5 = document.createElement("div");
var div6 = document.createElement("div");
var a1 = document.createElement("a");
var a2 = document.createElement("a");
var a3 = document.createElement("a");
var a4 = document.createElement("a");
var a5 = document.createElement("a");
var a6 = document.createElement("a");
var txt1 = document.createTextNode("ZenTech");
var txt2 = document.createTextNode("Home");
var txt3 = document.createTextNode("Work");
var txt4 = document.createTextNode("Services");
var txt5 = document.createTextNode("KrishalBasnet");
var txt6 = document.createTextNode("Contact");
a1.classList.add("baritem", "logo_text");
a2.classList.add("baritem");
a3.classList.add("baritem");
a4.classList.add("baritem");
a5.classList.add("baritem");
a6.classList.add("baritem");
a1.setAttribute("href", "index.html");
a2.setAttribute("href", "index.html");
a3.setAttribute("href", "work.html");
a4.setAttribute("href", "services.html");
a5.setAttribute("href", "../index.html");
a6.setAttribute("href", "../contact.html");
div.appendChild(div1);
div.appendChild(div2);
div.appendChild(div3);
div.appendChild(div4);
div.appendChild(div5);
div.appendChild(div6);
div1.appendChild(a1);
div2.appendChild(a2);
div3.appendChild(a3);
div4.appendChild(a4);
div5.appendChild(a5);
div6.appendChild(a6);
a1.appendChild(txt1);
a2.appendChild(txt2);
a3.appendChild(txt3);
a4.appendChild(txt4);
a5.appendChild(txt5);
a6.appendChild(txt6);
div2.classList.add("f56");
div3.classList.add("f56");
div4.classList.add("f56");
div5.classList.add("f56");
div6.classList.add("f56");
